### ISSUE TITLE
class out of range during import

### ISSUE THREAD

**Issue by xackery** [Akkadius/eqemu-monocle#2]
Reading file 'feerrott2_npc_2019-02-16-19-22-45.csv' time: 2019-02-16-19-22-45

   Illuminate\Database\QueryException  : SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'class' at row 1 (SQL: insert into `npc_types` (`id`, `bodytype`, `class`, `drakkin_de
tails`, `drakkin_heritage`, `drakkin_tattoo`, `face`, `gender`, `lastname`, `level`, `luclin_beard`, `luclin_beardcolor`, `luclin_eyecolor`, `luclin_eyecolor2`, `luclin_haircolor`, `luclin_hairstyle`, `name`
, `race`, `size`, `texture`, `d_melee_texture1`, `d_melee_texture2`, `STA`, `STR`, `DEX`, `AGI`, `_INT`, `WIS`, `CHA`, `MR`, `CR`, `FR`, `DR`, `PR`, `Corrup`, `PhR`, `attack_delay`, `runspeed`, `untargetable
`, `see_invis`) values (700145, 0, 16711680, 1, 0, 0, 255, 115, , 0, 156, 255, 255, 248, 255, 40, a_restless_spirit, 0, 6.000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.325, 0, 0))

  at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'class' at row 1")
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

**Comment by xackery** [comment]
I simplified the import dump to try to isolate this better: 
[Feerrott2_NPC_2019-02-18-11-31-24.zip](https://github.com/Akkadius/eqemu-monocle/files/2923068/Feerrott2_NPC_2019-02-18-11-31-24.zip)
Reading file 'feerrott2_npc_2019-02-18-11-31-24.csv' time: 2019-02-18-11-31-24

   Illuminate\Database\QueryException  : SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'class' at row 1 (SQL: insert into `npc_types` (`id`, `bodytype`, `class`, `drakkin_de
tails`, `drakkin_heritage`, `drakkin_tattoo`, `face`, `gender`, `lastname`, `level`, `luclin_beard`, `luclin_beardcolor`, `luclin_eyecolor`, `luclin_eyecolor2`, `luclin_haircolor`, `luclin_hairstyle`, `name`
, `race`, `size`, `texture`, `d_melee_texture1`, `d_melee_texture2`, `STA`, `STR`, `DEX`, `AGI`, `_INT`, `WIS`, `CHA`, `MR`, `CR`, `FR`, `DR`, `PR`, `Corrup`, `PhR`, `attack_delay`, `runspeed`, `untargetable
`, `see_invis`) values (700147, 0, -2013265920, -1939633151, 0, 0, 255, 10, , 128, 156, 255, 255, 248, 255, 40, #Investigator_Vekman, 255, 5.700000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.32
5, 0, 0))

 Exception trace:

  1   PDOException::("SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'class' at row 1")


so.. investigator spelner and elgron imported fine, but Vekman errored on class..
class is 14th from end
looks like a column was added or a misalignment happened? 

get_class seems to be right, i think the columns are off alignment on export? 
"JumpStrength","SwimStrength","SpeedMultiplier","AreaFriction","AccelerationFriction","FloorHeight","bSinksInWater","PlayerTimeStamp /* doesn't update when on a Vehicle (mounts/boats etc) */","LastTimeIdle","Lastname[0x20]","AreaHPRegenMod /*from guild hall pools etc. */","AreaEndRegenMod","AreaManaRegenMod","Y","X","Z","SpeedY","SpeedX","SpeedZ","SpeedRun","Heading","Angle","AccelAngle","SpeedHeading","CameraAngle","UnderWater /*LastHeadEnvironmentType */","LastBodyEnvironmentType","LastFeetEnvironmentType","HeadWet /*these really are environment related, like lava as well for example */","FeetWet","BodyWet","LastBodyWet","Name[0x40] /* ie priest_of_discord00 */","DisplayedName[0x40] /* ie Priest of Discord*/","PossiblyStuck /* never seen this be 1 so maybe it was used a a point but not now... */","Type","BodyType /* this really should be renamed to charprops or something its broken anyway*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","CharPropFiller[0xc] /* well since the above is a CharacterPropertyHash we have to pad here...*/","AvatarHeight /* height of avatar from groundwhen standing*/","Height","Width","Length","SpawnID","PlayerState /* 0=Idle 1=Open 2=WeaponSheathed 4=Aggressive 8=ForcedAggressive 0x10=InstrumentEquipped 0x20=Stunned 0x40=PrimaryWeaponEquipped 0x80=SecondaryWeaponEquipped */","Vehicle /* NULL until you collide with a vehicle (boat,airship etc) */","Mount /* NULL if no mount present */","Rider /* _SPAWNINFO of mount's rider */","Unknown0x015c","Targetable /* true if mob is targetable */","bTargetCyclable","bClickThrough","bBeingFlung","FlingActiveTimer","FlingTimerStart","bFlingSomething","FlingY","FlingX","FlingZ","bFlingSnapToDest","SplineID","SplineRiderID","ParticleCastStartTime","ParticleCastDuration","ParticleVisualSpellNum","MeleeRadius // used by GetMeleeRange","CollisionCounter","CachedFloorLocationY","CachedFloorLocationX","CachedFloorLocationZ","CachedFloorHeight","CachedCeilingLocationY","CachedCeilingLocationX","CachedCeilingLocationZ","CachedCeilingHeight","Animation /* Current Animation Playing. */","NextAnim","CurrLowerBodyAnim","NextLowerBodyAnim","CurrLowerAnimVariation","CurrAnimVariation","CurrAnimRndVariation","Loop3d_SoundID","Step_SoundID","CurLoop_SoundID","Idle3d1_SoundID","Idle3d2_SoundID","Jump_SoundID","Hit1_SoundID","Hit2_SoundID","Hit3_SoundID","Hit4_SoundID","Gasp1_SoundID","Gasp2_SoundID","Drown_SoundID","Death_SoundID","Attk1_SoundID","Attk2_SoundID","Attk3_SoundID","Walk_SoundID","Run_SoundID","Crouch_SoundID","Swim_SoundID","TreadWater_SoundID","Climb_SoundID","Sit_SoundID","Kick_SoundID","Bash_SoundID","FireBow_SoundID","MonkAttack1_SoundID","MonkAttack2_SoundID","MonkSpecial_SoundID","PrimaryBlunt_SoundID","PrimarySlash_SoundID","PrimaryStab_SoundID","Punch_SoundID","Roundhouse_SoundID","SecondaryBlunt_SoundID","SecondarySlash_SoundID","SecondaryStab_SoundID","SwimAttack_SoundID","TwoHandedBlunt_SoundID","TwoHandedSlash_SoundID","TwoHandedStab_SoundID","SecondaryPunch_SoundID","JumpAcross_SoundID","WalkBackwards_SoundID","CrouchWalk_SoundID","LastHurtSound","LastWalkTime//used for animations","ShipRelated//ID? look into.","RightHolding//Nothing=0 Other/Weapon=1 shield=2","LeftHolding//old Holding","DeathAnimationFinishTime","bRemoveCorpseAfterDeathAnim//0x1274 for sure used by /hidecorpse","LastBubblesTime","LastBubblesTime1","LastColdBreathTime","LastParticleUpdateTime","MercID //IT IS 0x1288 //if the spawn is player and has a merc up this is it's spawn ID -eqmule 16 jul 2014","ContractorID //if the spawn is a merc this is its contractor's spawn ID -eqmule 16 jul 2014","CeilingHeightAtCurrLocation","bInstantHPGaugeChange","LastUpdateReceivedTime","MaxSpeakDistance","WalkSpeed //how much we will slow down while sneaking","bHideCorpse //IT IS 0x12a8","AssistName[0x40]","InvitedToGroup //IT IS 12E9!","GroupMemberTargeted //12ec for sure! // 0xFFFFFFFF if no target, else 1 through 5","bRemovalPending","EmitterScalingRadius //0x12f8 FOR SURE","DefaultEmitterID","bDisplayNameSprite","bIdleAnimationOff","bIsInteractiveObject","InteractiveObjectModelName[0x80]","InteractiveObjectOtherName[0x80]","InteractiveObjectName[0x40]","PhysicsBeforeLastPort.Y","PhysicsBeforeLastPort.X","PhysicsBeforeLastPort.Z","PhysicsBeforeLastPort.SpeedY","PhysicsBeforeLastPort.SpeedX","PhysicsBeforeLastPort.SpeedZ","PhysicsBeforeLastPort.SpeedRun","PhysicsBeforeLastPort.Heading","PhysicsBeforeLastPort.Angle","PhysicsBeforeLastPort.AccelAngle","PhysicsBeforeLastPort.SpeedHeading","PhysicsBeforeLastPort.CameraAngle","notsure","Fellowship.Version","Fellowship.Version2//just place holders for now, ill fix these later","Fellowship.Version3","Fellowship.Version4","Fellowship.FellowshipID","Fellowship.FellowshipID2//guild does this to, need to figure out why","Fellowship.Leader[0x40]","Fellowship.MotD[0x400]","Fellowship.Members","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.FellowshipMember[i].WorldID","Fellowship.FellowshipMember[i].Name[0x40]","Fellowship.FellowshipMember[i].ZoneID","Fellowship.FellowshipMember[i].Level","Fellowship.FellowshipMember[i].Class","Fellowship.FellowshipMember[i].LastOn// FastTime() timestamp","Fellowship.Somedata[i].Strings[0x20]","Fellowship.bExpSharingEnabled[0xc]","Fellowship.bSharedExpCapped[0xc]","Fellowship.Sync","CampfireY//see 585D7A in jul 9 2018 test","CampfireX","CampfireZ","CampfireZoneID // zone ID where campfire is","CampfireTimestamp // CampfireTimestamp-FastTime()=time left on campfire","CampfireTimestamp2","FellowShipID","FellowShipID2","CampType","Campfire","SeeInvis[0]","SeeInvis[1]","SeeInvis[2]","Equipment.Head.ID //idfile on Lucy","Equipment.Head.Var","Equipment.Head.Material","Equipment.Head.NewArmorID","Equipment.Head.NewArmorType","Equipment.Chest.ID //idfile on Lucy","Equipment.Chest.Var","Equipment.Chest.Material","Equipment.Chest.NewArmorID","Equipment.Chest.NewArmorType","Equipment.Arms.ID //idfile on Lucy","Equipment.Arms.Var","Equipment.Arms.Material","Equipment.Arms.NewArmorID","Equipment.Arms.NewArmorType","Equipment.Wrists.ID //idfile on Lucy","Equipment.Wrists.Var","Equipment.Wrists.Material","Equipment.Wrists.NewArmorID","Equipment.Wrists.NewArmorType","Equipment.Hands.ID //idfile on Lucy","Equipment.Hands.Var","Equipment.Hands.Material","Equipment.Hands.NewArmorID","Equipment.Hands.NewArmorType","Equipment.Legs.ID //idfile on Lucy","Equipment.Legs.Var","Equipment.Legs.Material","Equipment.Legs.NewArmorID","Equipment.Legs.NewArmorType","Equipment.Feet.ID //idfile on Lucy","Equipment.Feet.Var","Equipment.Feet.Material","Equipment.Feet.NewArmorID","Equipment.Feet.NewArmorType","Equipment.Primary.ID //idfile on Lucy","Equipment.Primary.Var","Equipment.Primary.Material","Equipment.Primary.NewArmorID","Equipment.Primary.NewArmorType","Equipment.Offhand.ID //idfile on Lucy","Equipment.Offhand.Var","Equipment.Offhand.Material","Equipment.Offhand.NewArmorID","Equipment.Offhand.NewArmorType","bIsPlacingItem","bGMCreatedNPC","ObjectAnimationID","bInteractiveObjectCollidable","InteractiveObjectType","SoundIDs[0]//0x28 bytes","SoundIDs[1]//0x28 bytes","SoundIDs[2]//0x28 bytes","SoundIDs[3]//0x28 bytes","SoundIDs[4]//0x28 bytes","SoundIDs[5]//0x28 bytes","SoundIDs[6]//0x28 bytes","SoundIDs[7]//0x28 bytes","SoundIDs[8]//0x28 bytes","SoundIDs[9]//0x28 bytes","LastHistorySentTime","CurrentBardTwistIndex//see 63CB2A in jul 9 2018 test","SpawnStatus[0]//todo: look closer at these i think they can show like status of mobs slowed, mezzed etc, but not sure","SpawnStatus[1]//todo: look closer at these i think they can show like status of mobs slowed, mezzed etc, but not sure","SpawnStatus[2]//todo: look closer at these i think they can show like status of mobs slowed, mezzed etc, but not sure","SpawnStatus[3]//todo: look closer at these i think they can show like status of mobs slowed, mezzed etc, but not sure","SpawnStatus[4]//todo: look closer at these i think they can show like status of mobs slowed, mezzed etc, but not sure","SpawnStatus[5]//todo: look closer at these i think they can show like status of mobs slowed, mezzed etc, but not sure","BannerIndex0//guild banners","BannerIndex1","BannerTint0","BannerTint1","MountAnimationRelated","bGuildShowAnim//or sprite? need to check","bWaitingForPort//check this","mActorClient.TextureType","mActorClient.Material","mActorClient.Variation","mActorClient.HeadType","mActorClient.FaceStyle","mActorClient.HairColor","mActorClient.FacialHairColor","mActorClient.EyeColor1","mActorClient.EyeColor2","mActorClient.HairStyle","mActorClient.FacialHair","mActorClient.Race","mActorClient.Race2","mActorClient.Class","mActorClient.Gender","mActorClient.ActorDef[0x40]","mActorClient.ArmorColor[0]","mActorClient.ArmorColor[1]","mActorClient.ArmorColor[2]","mActorClient.ArmorColor[3]","mActorClient.ArmorColor[4]","mActorClient.ArmorColor[5]","mActorClient.ArmorColor[6]","mActorClient.ArmorColor[7]","mActorClient.ArmorColor[8]","mActorClient.bShowHelm","mActorClient.Heritage","mActorClient.Tattoo","mActorClient.Details","GetClass()","GetId()","LastCastNum","RunSpeed","HPMax","CharClass","WarCry","Deity","MyWalkSpeed","GetMeleeRangeVar1","FindBits","Title[0x80]","Level","Light"

**Comment by xackery** [comment]
wrote a quick patch of 
https://github.com/Akkadius/eqemu-monocle/blob/master/app/Services/ZoneDataDumpImportService.php#L181
below class import
if ($npc->class<1) $npc->class = 1;
if ($npc->class>100) $npc->class = 1;

to sanitize values for now, just default to warrior

**Comment by Akkadius** [comment]
Something is really going on with the data dumps that you have, there are a lot of uninitialized values which is in the realm of the MQ2 plugin itself
