### ISSUE TITLE
max_level out of range

### ISSUE THREAD

**Issue by xackery** [Akkadius/eqemu-monocle#3]
After patching #2 got this next error, using same csv i attached on previous issue
Reading file 'feerrott2_npc_2019-02-18-11-31-24.csv' time: 2019-02-18-11-31-24

   Illuminate\Database\QueryException  : SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'maxlevel' at row 1 (SQL: update `npc_types` set `maxlevel` = 137 where `id` = 700148)

**Comment by xackery** [comment]
to temp patch this, I just wrote below this line: https://github.com/Akkadius/eqemu-monocle/blob/master/app/Services/ZoneDataDumpImportService.php#L366

			if ($npc_level_max>127) $npc_level_max = 120;

to upper bounds level max to 120.

**Comment by Akkadius** [comment]
I'd rather not clamp levels if we are getting higher level values from the dumps, we need to adjust our schema
