### ISSUE TITLE
level cannot be null

### ISSUE THREAD

**Issue by xackery** [Akkadius/eqemu-monocle#4]
after applying the quick patches noted in #2 and #3 , I took another dump with the full zone data (attached) 
[Feerrott2_NPC_2019-02-16-19-22-45.zip](https://github.com/Akkadius/eqemu-monocle/files/2923095/Feerrott2_NPC_2019-02-16-19-22-45.zip)

and got the following error:

root@276e32b33eb7:/var/www# php artisan zonetools:zone-delete feerrott2 0 npc
root@276e32b33eb7:/var/www# php artisan zonetools:dump-import feerrott2 0 npc

Reading file 'feerrott2_npc_2019-02-16-19-22-45.csv' time: 2019-02-16-19-22-45

   Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'level' cannot be null (SQL: insert into `npc_types` (`id`, `bodytype`, `class`, `drakkin_details`, `drak
kin_heritage`, `drakkin_tattoo`, `face`, `gender`, `lastname`, `level`, `luclin_beard`, `luclin_beardcolor`, `luclin_eyecolor`, `luclin_eyecolor2`, `luclin_haircolor`, `luclin_hairstyle`, `name`, `race`, `si
ze`, `texture`, `d_melee_texture1`, `d_melee_texture2`, `STA`, `STR`, `DEX`, `AGI`, `_INT`, `WIS`, `CHA`, `MR`, `CR`, `FR`, `DR`, `PR`, `Corrup`, `PhR`, `attack_delay`, `runspeed`, `untargetable`, `see_invis
`) values (700150, 0, 1, 0.000000, -1047922032, 1083808175, 1107296000, 0, , , 0, ╔, 1100165946, 1101769470, 74, 1114352836, a_froglok_corpse, 0, 5.000000, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 1.325, 0, 0))

**Comment by xackery** [comment]
looks like the data being imported needs a lot of TLC, too 
![image](https://user-images.githubusercontent.com/845670/53695291-5ac3f780-3d6e-11e9-9fb1-69757d760bbb.png)

**Comment by Akkadius** [comment]
This is more of an issue of the data that the dumper is creating
