### ISSUE TITLE
feature request: throw line number when csv exception occurs

### ISSUE THREAD

**Issue by xackery** [Akkadius/eqemu-monocle#5]
foreach ($this->data_dump_reader_service->getCsvData() as $row) {

print_r($row) just dumps the row data..  what's a way to get line number? 

this code is layering this and vs code can't go to declarations, so.. i'm just not gonna bother adn ask for a feature request haha

was trying to wrap the foreach above into something like
try {
} catch (Exception $e) {
				print_r($this->data_dump_reader_service->linenumber?);
				throw $e;
			}

**Comment by Akkadius** [comment]
If we're getting exceptions then I need to work through the dump and why it's throwing the exception
